# ============================================================
# .
# ============================================================

# --- Gmail: dùng để gửi email OTP đăng nhập ---
# Tạo App Password tại: https://myaccount.google.com/apppasswords
# (Yêu cầu tài khoản Google đã bật xác thực 2 bước)
mail.from.email=nguyensonglong0121@gmail.com
mail.app.password=qjrm uenm lpzv jips


# --- Google OAuth2 Login ---
# Lấy Client ID / Client Secret tại: https://console.cloud.google.com/apis/credentials
google.client.id=923648379028-4de1dn9ug14nk5jp2it8euufhlduqlpo.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/CayCanhWeb/auth/google/callback

# --- GHN (Giao Hàng Nhanh) API ---
# Đăng ký tài khoản dev + lấy Token/ShopId tại: https://dev-online-gateway.ghn.vn
ghn.token=e3b8dae3-50db-11f1-a973-aee5264794df
ghn.shop.id=200907
